import stanza
import time

stanza.download("en")
time.sleep(15)
stanza.download("de")
time.sleep(15)
# stanza.download("ar")
# time.sleep(15)
# stanza.download("be")
# time.sleep(15)
# stanza.download("fr")
# time.sleep(15)
# stanza.download("it")
# time.sleep(15)
# stanza.download("ja")
# time.sleep(15)
# stanza.download("pt")
# time.sleep(15)
# stanza.download("ru")
# time.sleep(15)
# stanza.download("es")
# time.sleep(15)
# stanza.download("uk")
