

name: CI
  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        python-version: [3.9]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # python -m pip install -e .
        # python -m pip install -r requirements-dev.txt
    - name: Install treetagger
      run: |
        mkdir treetagger
        cd treetagger
        if [runner.os == 'Linux']; then
          wget http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-linux-3.2.4.tar.gz
        elif [runner.os == 'Windows']; then
          wget https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-windows-3.2.3.zip
        # curl -sSL "$HOME_URL/tree-tagger-linux-3.2.4.tar.gz" --output tree-tagger-linux-3.2.4.tar.gz
        # curl -sSL "${HOME_URL}/tagger-scripts.tar.gz" --output tagger-scripts.tar.gz
        # curl -sSL "${HOME_URL}/install-tagger.sh" --output install-tagger.sh
        # curl -sSL "${HOME_URL}/german.par.gz" --output german.par.gz
        # curl -sSL "${HOME_URL}/english.par.gz" --output english.par.gz
        # sh install-tagger.sh
        cd ..
      env:
        HOME_URL: http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data
    - name: Get the models 
      run: |
        source nlpannotator/test/setup_tests.sh
        python -m spacy download en_core_web_md
        python -m spacy download de_core_news_md
    - name: Create test directories
      run: |
        mkdir nlpannotator/test/corpora
        mkdir nlpannotator/test/registry
        mkdir nlpannotator/test/out
    - name: Run pytest
      run: |
        cd nlpannotator
        # python -m pytest -s --cov=. --cov-report=xml
    # - name: Upload coverage
    #   uses: codecov/codecov-action@v1
    #   with:
    #     fail_ci_if_error: true
    #     files: nlpannotator/coverage.xml
