

name: CI
  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]
        python-version: [3.9]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install -r requirements-dev.txt
    - name: Install treetagger
      shell: bash
      env:
        myurl: http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data
      run: |
        mkdir treetagger
        cd treetagger
        if [ "$RUNNER_OS" = "Linux" ]; then
            echo "Linux"
            curl -sSLO "$myurl"/tree-tagger-linux-3.2.4.tar.gz
        elif [ "$RUNNER_OS" = "Windows" ]; then
            echo "Windows"
            curl -sSLO "$myurl"/tree-tagger-windows-3.2.3.zip
        elif [ "$RUNNER_OS" = "macOS" ]; then
            echo "MacOS"
            curl -sSLO "$myurl"/tree-tagger-MacOSX-Intel-3.2.3.zip
        fi
        curl -sSLO "$myurl"/tagger-scripts.tar.gz
        curl -sSLO "$myurl"/install-tagger.sh
        curl -sSLO "$myurl"/german.par.gz
        curl -sSLO "$myurl"/english.par.gz
        sh install-tagger.sh
        cd ..
    - name: Get the models 
      run: |
        source nlpannotator/test/setup_tests.sh
        python -m spacy download en_core_web_md
        python -m spacy download de_core_news_md
    - name: Create test directories
      run: |
        mkdir nlpannotator/test/corpora
        mkdir nlpannotator/test/registry
        mkdir nlpannotator/test/out
    - name: Run pytest
      run: |
        cd nlpannotator
        python -m pytest -s --cov=. --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        files: nlpannotator/coverage.xm